[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "12.16.1"
[[redirects]]
  from = "https://daksh-website.netlify.com"
  to = "https://daksh.me"
  status = 301
  force = true
[[redirects]]
  from = "/dotfiles"
  to = "https://github.com/dakshshah96/dotfiles"
