[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "12.16.1"
[[redirects]]
  from = "https://daksh-website.netlify.com"
  to = "https://daksh.me"
  status = 301
  force = true
[[redirects]]
  from = "/dotfiles"
  to = "https://github.com/dakshshah96/dotfiles"
[[redirects]]
  from = "/github"
  to = "https://github.com/dakshshah96/"
[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/dakshshah96"
[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/dakshshah/"
